version: 0.1

phases:
  install:
    commands:
      - printenv
      - rm -rf node_modules
      - npm install
  build:
    commands:
      - npm run build -prod
  post_build:
    commands:
      - aws --region us-east-1 s3 sync ./dist/ s3://arn:aws:s3:::ci-cd-practice/ --acl=public-read --delete
